apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ce-proxy
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: ko://github.com/mikehelmick/ceproxy
          env:
          - name: broker
            value: http://default-broker.default.svc.cluster.local
